# Generated by Django 3.0.3 on 2020-02-20 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=254, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('surname', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=20)),
                ('department', models.CharField(choices=[('MR', 'MR'), ('MRS', 'MRS'), ('MS', 'MS'), ('DR', 'DR'), ('CHIEF', 'CHIEF'), ('COL', 'COL')], max_length=30, null=True)),
                ('role', models.CharField(choices=[('BAR1', 'BAR1'), ('DEX', 'DEX'), ('EXE', 'EXE'), ('SUT', 'SUT')], max_length=10, null=True)),
                ('title', models.CharField(choices=[('BAR1', 'BAR1'), ('DEX', 'DEX'), ('EXE', 'EXE'), ('SUT', 'SUT')], max_length=10, null=True)),
                ('birth_date', models.DateField(null=True)),
                ('years_of_practice', models.IntegerField(null=True)),
                ('gender', models.CharField(choices=[('BAR1', 'BAR1'), ('DEX', 'DEX'), ('EXE', 'EXE'), ('SUT', 'SUT')], max_length=8, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
