# Generated by Django 3.0.3 on 2020-02-20 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0002_auto_20200220_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='department',
            field=models.CharField(blank=True, choices=[('Gen', 'Gynacologist'), ('Gym', 'Gym Instructor')], max_length=30, null=True),
        ),
    ]
