# Generated by Django 3.0.3 on 2020-02-20 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalRecord', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmedicalrecord',
            name='current_symtomps',
            field=models.CharField(choices=[('Coughing', 'Coughing'), ('Headache', 'Headache')], max_length=10),
        ),
    ]
