# Generated by Django 3.0.3 on 2020-02-21 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalRecord', '0003_auto_20200221_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmedicalrecord',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='patientmedicalrecord',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientmedicalrecord',
            name='current_symtomps',
            field=models.CharField(choices=[('Malaria', 'Malaria'), ('Headache', 'Headache')], max_length=10),
        ),
    ]
